export interface TourismState {
  id: string;
  state: string;
  eyebrow: string;
  title: string;
  description: string;
  categories: string[];
  image: string;
  portalUrl: string;
  portalLabel: string;
  holidayLabel: string;
  supportingTitle: string;
  supportingText: string;
}

/** Images live in public/obms, one file per state (named after the state). */
export const TOURISM_STATES: TourismState[] = [
  {
    id: "rajasthan",
    state: "Rajasthan",
    eyebrow: "Official monument tickets",
    title: "Explore Rajasthan's iconic sites",
    description:
      "Book forts, palaces, museums and wildlife experiences through Rajasthan's official tourism and ticketing portal.",
    categories: ["Forts & Palaces", "Wildlife", "Museums", "Light & Sound", "Composite Tickets"],
    image: "/obms/Rajasthan.png",
    portalUrl: "https://obms-tourist.rajasthan.gov.in/",
    portalLabel: "Book on OBMS",
    holidayLabel: "See Rajasthan holidays",
    supportingTitle: "Plan the trip around the tickets",
    supportingText:
      "Jaipur, Udaipur, Jodhpur and wildlife circuits work best when monument visits and hotel nights are planned together.",
  },
  {
    id: "kerala",
    state: "Kerala",
    eyebrow: "Official tourism",
    title: "Experience Kerala's backwaters & escapes",
    description:
      "Explore Kerala's backwaters, hill stations, beaches, wildlife and cultural experiences through the official tourism portal.",
    categories: ["Backwaters", "Hill Stations", "Beaches", "Wildlife", "Experiences"],
    image: "/obms/Kerala.png",
    portalUrl: "https://www.keralatourism.gov.in/",
    portalLabel: "Visit Kerala Tourism",
    holidayLabel: "See Kerala holidays",
    supportingTitle: "Plan your Kerala escape",
    supportingText: "Combine Kochi, Munnar, Thekkady and Alleppey into one seamless Tripime itinerary.",
  },
  {
    id: "goa",
    state: "Goa",
    eyebrow: "Official tourism",
    title: "Discover Goa beyond the beaches",
    description:
      "Explore beaches, heritage sites, water activities, nature and cultural experiences through Goa's official tourism resources.",
    categories: ["Beaches", "Heritage", "Water Activities", "Nature", "Experiences"],
    image: "/obms/Goa.png",
    portalUrl: "https://www.goa-tourism.com/",
    portalLabel: "Visit Goa Tourism",
    holidayLabel: "See Goa holidays",
    supportingTitle: "Build your Goa getaway",
    supportingText: "Pair beach stays with heritage, food, nightlife and experiences across North and South Goa.",
  },
  {
    id: "himachal-pradesh",
    state: "Himachal Pradesh",
    eyebrow: "Official tourism",
    title: "Explore the Himalayas",
    description:
      "Discover mountain towns, valleys, trekking routes, adventure activities and scenic escapes through Himachal Tourism.",
    categories: ["Mountains", "Trekking", "Adventure", "Hill Stations", "Nature"],
    image: "/obms/Himachal%20Pradesh.png",
    portalUrl: "https://himachaltourism.gov.in/",
    portalLabel: "Visit Himachal Tourism",
    holidayLabel: "See Himachal holidays",
    supportingTitle: "Plan your mountain escape",
    supportingText: "Build routes across Shimla, Manali, Spiti, Kasol and other Himalayan destinations.",
  },
  {
    id: "uttarakhand",
    state: "Uttarakhand",
    eyebrow: "Official tourism",
    title: "Discover the mountains & sacred trails",
    description:
      "Explore Himalayan destinations, pilgrimage routes, wildlife, lakes and adventure experiences across Uttarakhand.",
    categories: ["Himalayas", "Pilgrimage", "Wildlife", "Lakes", "Adventure"],
    image: "/obms/Uttarakhand.png",
    portalUrl: "https://uttarakhandtourism.gov.in/",
    portalLabel: "Visit Uttarakhand Tourism",
    holidayLabel: "See Uttarakhand holidays",
    supportingTitle: "Plan your Uttarakhand journey",
    supportingText:
      "Combine Rishikesh, Mussoorie, Nainital, Jim Corbett and Himalayan destinations into one itinerary.",
  },
  {
    id: "jammu-kashmir",
    state: "Jammu & Kashmir",
    eyebrow: "Official tourism",
    title: "Experience Kashmir's landscapes",
    description:
      "Discover Kashmir's valleys, lakes, mountains, gardens and adventure experiences through official tourism resources.",
    categories: ["Kashmir", "Mountains", "Lakes", "Adventure", "Heritage"],
    image: "/obms/J%26K.png",
    portalUrl: "https://www.jktdc.co.in/",
    portalLabel: "Visit J&K Tourism",
    holidayLabel: "See Kashmir holidays",
    supportingTitle: "Plan your Kashmir escape",
    supportingText: "Build a route across Srinagar, Gulmarg, Pahalgam and other destinations.",
  },
  {
    id: "sikkim",
    state: "Sikkim",
    eyebrow: "Official tourism",
    title: "Discover Sikkim's Himalayan beauty",
    description: "Explore monasteries, mountain passes, valleys, lakes and Himalayan experiences across Sikkim.",
    categories: ["Himalayas", "Monasteries", "Adventure", "Lakes", "Permits"],
    image: "/obms/Sikkim.png",
    portalUrl: "https://www.sikkimtourism.gov.in/",
    portalLabel: "Visit Sikkim Tourism",
    holidayLabel: "See Sikkim holidays",
    supportingTitle: "Plan your Himalayan journey",
    supportingText: "Combine Gangtok, Nathula, Pelling and North Sikkim into a seamless itinerary.",
  },
  {
    id: "maharashtra",
    state: "Maharashtra",
    eyebrow: "Official tourism",
    title: "Discover Maharashtra's heritage & escapes",
    description: "Explore forts, caves, beaches, hill stations, cities and cultural attractions across Maharashtra.",
    categories: ["Forts", "Heritage", "Beaches", "Hill Stations", "Caves"],
    image: "/obms/Maharashtra.png",
    portalUrl: "https://maharashtratourism.gov.in/",
    portalLabel: "Visit Maharashtra Tourism",
    holidayLabel: "See Maharashtra holidays",
    supportingTitle: "Plan your Maharashtra trip",
    supportingText: "Combine Mumbai, Lonavala, Mahabaleshwar, Ajanta and Ellora into one trip.",
  },
  {
    id: "gujarat",
    state: "Gujarat",
    eyebrow: "Official tourism",
    title: "Explore Gujarat's heritage & landscapes",
    description: "Discover the Rann of Kutch, heritage cities, temples, wildlife and cultural attractions across Gujarat.",
    categories: ["Rann of Kutch", "Heritage", "Wildlife", "Temples", "Culture"],
    image: "/obms/Gujarat.png",
    portalUrl: "https://www.gujarattourism.com/",
    portalLabel: "Visit Gujarat Tourism",
    holidayLabel: "See Gujarat holidays",
    supportingTitle: "Plan your Gujarat journey",
    supportingText: "Explore Ahmedabad, Kutch, Dwarka, Somnath and other major destinations.",
  },
  {
    id: "madhya-pradesh",
    state: "Madhya Pradesh",
    eyebrow: "Official tourism",
    title: "Explore India's heartland",
    description: "Discover wildlife, heritage, temples, UNESCO sites and historic cities across Madhya Pradesh.",
    categories: ["Wildlife", "Heritage", "Temples", "UNESCO Sites", "Culture"],
    image: "/obms/Madhya%20Pradesh.png",
    portalUrl: "https://www.mptourism.com/",
    portalLabel: "Visit MP Tourism",
    holidayLabel: "See MP holidays",
    supportingTitle: "Plan your Madhya Pradesh trip",
    supportingText: "Combine Khajuraho, Ujjain, Orchha, Kanha and other destinations.",
  },
  {
    id: "uttar-pradesh",
    state: "Uttar Pradesh",
    eyebrow: "Official tourism",
    title: "Discover India's historic heart",
    description: "Explore the Taj Mahal, Varanasi, Ayodhya, heritage sites and spiritual destinations across Uttar Pradesh.",
    categories: ["Taj Mahal", "Heritage", "Spiritual", "Culture", "Historic Sites"],
    image: "/obms/Uttar%20Pradesh.png",
    portalUrl: "https://www.uptourism.gov.in/",
    portalLabel: "Visit UP Tourism",
    holidayLabel: "See UP holidays",
    supportingTitle: "Plan your Uttar Pradesh journey",
    supportingText: "Build a route across Agra, Varanasi, Ayodhya, Lucknow and other destinations.",
  },
  {
    id: "tamil-nadu",
    state: "Tamil Nadu",
    eyebrow: "Official tourism",
    title: "Explore temples, culture & coastlines",
    description: "Discover ancient temples, heritage towns, beaches, hill stations and cultural experiences across Tamil Nadu.",
    categories: ["Temples", "Heritage", "Beaches", "Hill Stations", "Culture"],
    image: "/obms/Tamil%20Nadu.png",
    portalUrl: "https://www.tamilnadutourism.com/",
    portalLabel: "Visit Tamil Nadu Tourism",
    holidayLabel: "See Tamil Nadu holidays",
    supportingTitle: "Plan your Tamil Nadu journey",
    supportingText: "Combine Chennai, Madurai, Ooty, Rameswaram and other destinations.",
  },
  {
    id: "karnataka",
    state: "Karnataka",
    eyebrow: "Official tourism",
    title: "Discover Karnataka's heritage & nature",
    description: "Explore Hampi, Mysore, Coorg, beaches, waterfalls and historic destinations across Karnataka.",
    categories: ["Hampi", "Heritage", "Beaches", "Wildlife", "Hill Stations"],
    image: "/obms/Karnataka.png",
    portalUrl: "https://www.karnatakatourism.org/",
    portalLabel: "Visit Karnataka Tourism",
    holidayLabel: "See Karnataka holidays",
    supportingTitle: "Plan your Karnataka journey",
    supportingText: "Combine Bengaluru, Mysore, Hampi, Coorg and coastal destinations.",
  },
  {
    id: "telangana",
    state: "Telangana",
    eyebrow: "Official tourism",
    title: "Discover Hyderabad & beyond",
    description: "Explore heritage, food, forts, museums, temples and experiences across Telangana.",
    categories: ["Hyderabad", "Heritage", "Forts", "Culture", "Experiences"],
    image: "/obms/Telangana.png",
    portalUrl: "https://tourism.telangana.gov.in/",
    portalLabel: "Visit Telangana Tourism",
    holidayLabel: "See Telangana holidays",
    supportingTitle: "Plan your Telangana trip",
    supportingText: "Explore Hyderabad, Warangal, Ramappa and other cultural destinations.",
  },
  {
    id: "odisha",
    state: "Odisha",
    eyebrow: "Official tourism",
    title: "Explore temples, beaches & culture",
    description: "Discover Puri, Konark, ancient temples, beaches, wildlife and cultural experiences across Odisha.",
    categories: ["Temples", "Heritage", "Beaches", "Wildlife", "Culture"],
    image: "/obms/Odisha.png",
    portalUrl: "https://odishatourism.gov.in/",
    portalLabel: "Visit Odisha Tourism",
    holidayLabel: "See Odisha holidays",
    supportingTitle: "Plan your Odisha journey",
    supportingText: "Combine Bhubaneswar, Puri, Konark and other cultural destinations.",
  },
  {
    id: "west-bengal",
    state: "West Bengal",
    eyebrow: "Official tourism",
    title: "From Kolkata to the Himalayas",
    description: "Explore Kolkata, Darjeeling, Sundarbans, heritage sites and cultural experiences across West Bengal.",
    categories: ["Darjeeling", "Sundarbans", "Heritage", "Culture", "Wildlife"],
    image: "/obms/West%20Bengal.png",
    portalUrl: "https://wbtourism.gov.in/",
    portalLabel: "Visit West Bengal Tourism",
    holidayLabel: "See West Bengal holidays",
    supportingTitle: "Plan your West Bengal journey",
    supportingText: "Combine Kolkata, Darjeeling, Kalimpong and Sundarbans.",
  },
  {
    id: "assam",
    state: "Assam",
    eyebrow: "Official tourism",
    title: "Discover Assam's wildlife & culture",
    description: "Explore Kaziranga, tea gardens, river landscapes and cultural experiences across Assam.",
    categories: ["Kaziranga", "Wildlife", "Tea Gardens", "Culture", "Nature"],
    image: "/obms/Assam.png",
    portalUrl: "https://tourism.assam.gov.in/",
    portalLabel: "Visit Assam Tourism",
    holidayLabel: "See Assam holidays",
    supportingTitle: "Plan your Assam journey",
    supportingText: "Combine Kaziranga, Guwahati, Majuli and tea country.",
  },
  {
    id: "meghalaya",
    state: "Meghalaya",
    eyebrow: "Official tourism",
    title: "Discover waterfalls & living root bridges",
    description: "Explore Shillong, Cherrapunji, waterfalls, caves and unique natural attractions across Meghalaya.",
    categories: ["Waterfalls", "Caves", "Nature", "Adventure", "Culture"],
    image: "/obms/Meghalaya.png",
    portalUrl: "https://www.meghalayatourism.in/",
    portalLabel: "Visit Meghalaya Tourism",
    holidayLabel: "See Meghalaya holidays",
    supportingTitle: "Plan your Meghalaya adventure",
    supportingText: "Combine Shillong, Cherrapunji, Dawki and surrounding natural attractions.",
  },
];
